# Generated by Django 4.0.4 on 2022-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='defualt_pic.png', upload_to='profile_images'),
        ),
    ]
